apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  # deployment resource labels
  labels:
    component: mysql
    project: expense
    tier: db
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db
  # pod defination
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: devopskk/mysql:{{ .Values.deployment.imageVersion }}