apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # deployment resource labels
  labels:
    component: backend
    project: expense
    tier: app
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app
  # pod defination
  template:
    metadata:
      labels:
        component: backend
        project: expense
        tier: app
    spec:
      containers:
      - name: backend
        image: devopskk/backend:{{ .Values.deployment.imageVersion }}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: backend
        resources:
          {{- toYaml .Values.deployment.resourcesize | nindent 10 }}

# we called entire block above.
